name: Pipeline

on:
  push:
  pull_request:
    branches: [main]
    types: [review_requested, ready_for_review]
    
jobs:
  DraftPR:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.draft == true
    
    steps:
      - uses: actions/checkout@v3      
      - name: Test with pytest
        id: Pytest
        
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py          
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success'      
        uses: jinmayamashita/ready-for-review@1.0.0     #change draft PR to normal PR 
        with:
          in-progress-label: 'InProgress'
          ready-for-review-label: 'ReadyForReview'
          repo-token: ${{ secrets.GIT_TOKEN }}
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success' && github.ref == 'refs/heads/main'          
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
  Tunel:
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "All ok"
        
  NormalPR:
    runs-on: ubuntu-latest
   # needs: DraftPR
    if: github.event.pull_request.draft != true && ${{ jobs.DraftPR.result != 'failure' }}
    
    steps:        
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub        
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
                  
      - name: Build and push       
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flaskapp1:latest

