name: Pipeline

on:
  push:
  pull_request:
    branches: [main]
    types: [review_requested, ready_for_review]
    
jobs:
  DraftPR:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == true
    
    steps:
      - uses: actions/checkout@v3      
      - name: Test with pytest
        id: Pytest
        
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py          
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success'      
        uses: jinmayamashita/ready-for-review@1.0.0     #change draft PR to normal PR 
        with:
          in-progress-label: 'InProgress'
          ready-for-review-label: 'ReadyForReview'
          repo-token: ${{ secrets.GIT_TOKEN }}
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success'          
        id: tag_version
        run: echo "hello"           
        
  NormalPR:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    
    steps:    
      - name: Login to Docker Hub
        #if: job.DraftPR.steps.Pytest.outcome == 'success'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Set up Docker Build
        #if: job.DraftPR.steps.Pytest.outcome == 'success'
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push 
        #if: job.DraftPR.steps.Pytest.outcome == 'success'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flaskapp1:latest
          
   #     uses: mathieudutour/github-tag-action@v6.0
   #     with:
   #       github_token: ${{ secrets.GIT_TOKEN }}
