name: DraftPR

on:
  push:
  pull_request:
    types: [review_requested, ready_for_review]
    
jobs:
  UnitTest:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.draft != true
    
    steps:
      - uses: actions/checkout@v3   
      
      - name: Test with pytest
        id: Pytest
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success' 
        run: echo "UT success !!"
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success'  
        id: tag
        
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "tazatag2"
          message: "Latest release"
  CheckTag: 
    runs-on: ubuntu-latest
    needs: [UnitTest]
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
        with:
          tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.
      
      
