name: DraftPR

on:
  push:
  pull_request:
    types: [review_requested, ready_for_review]
    
jobs:
  UnitTest:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.draft != true
    
    steps:
      - uses: actions/checkout@v3   
      
      - name: Test with pytest
        id: Pytest
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success' 
        run: echo "UT success !!"
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success'  
        id: tag
        
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: RC-25
        
  CheckTag: 
    runs-on: ubuntu-latest
    needs: [UnitTest]
    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
  
      
