name: DraftPR

on:
  push:
  pull_request:
    types: [review_requested, ready_for_review]
    
jobs:
  UnitTest:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.draft != true
    
    steps:
      - uses: actions/checkout@v3   
      
      - name: Test with pytest
        id: Pytest
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success' 
        run: echo "UT success !!"
        #uses: jinmayamashita/ready-for-review@1.0.0     #change draft PR to normal PR 
        #with:
        #  in-progress-label: 'InProgress'
        #  ready-for-review-label: 'ReadyForReview'
        #  repo-token: ${{ secrets.GIT_TOKEN }}
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success'          
        #id: tag_version
        #uses: mathieudutour/github-tag-action@v6.0
        #with:
        uses: Roang-zero1/github-create-release-action@v2
        with:
          version_regex: '^RC-[[:digit:]]$\n'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        #  github_token: ${{ secrets.GIT_TOKEN }}
        
  
