name: DraftPR

on:
  push:
  pull_request:
    types: [review_requested, ready_for_review]
    
jobs:
  UnitTest:
    runs-on: ubuntu-latest    
    if: github.event.pull_request.draft != true
    
    steps:
      - uses: actions/checkout@v3   
      
      - name: Test with pytest
        id: Pytest
        run: |
          pip install Flask
          pip install pytest
          pip install pytest-cov
          pytest test_hello.py
        continue-on-error: true
              
      - name: UT success
        if: steps.Pytest.outcome == 'success' 
        run: echo "UT success !!"
        
      - name: UT failure
        if: steps.Pytest.outcome != 'success'  
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
    # Optionally strip `v` prefix
          strip_v: true
      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}
        
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: "tazatag"
          message: "Latest release"
